#4184inat add updater field in json observation field value response
inaturalist/iNaturalistAPI pull request #480
Opened 2024-12-01 01:38 UTC by jotamayo97

this PR is for this task https://github.com/inaturalist/inaturalist/issues/4184

2025-01-28 19:38 UTC, kueda requested changes
Sorry, one minor change!

2025-01-28 19:38 UTC, kueda commented on lib/models/observation.js
> +
Shoot, forgot about this: please use 2-space indentation. Again, if your editor has eslint integration it should be alerting you about this. You can also run `npx eslint --fix lib/`

2025-02-14 00:03 UTC, kueda commented
@jotamayo97 are you still planning to work on this?

2025-02-14 00:07 UTC, jotamayo97 commented
> @jotamayo97 are you still planning to work on this?

Yes! Sorry, I’m currently travelling.
Next week I will apply all the requests 😎.
Thank you for waiting for me!

2025-02-18 12:53 UTC, jotamayo97 commented on lib/models/observation.js
> +
ups! sorry!
I already installed eslint :) thanks for the tip!

2025-02-25 23:25 UTC, merged